# Generated by Django 3.2.4 on 2021-07-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_customuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='hod',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuserprofile'),
        ),
    ]
