# Generated by Django 3.2.4 on 2021-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210704_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'User')], default=4),
        ),
    ]
