# Generated by Django 3.2.4 on 2021-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_filled_profile',
        ),
        migrations.AddField(
            model_name='hod',
            name='has_filled_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='has_filled_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_filled_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')]),
        ),
    ]
