# Generated by Django 3.2.4 on 2021-07-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210705_0346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserProfile',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
