# Generated by Django 3.2.4 on 2021-07-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210705_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
        migrations.AddField(
            model_name='student',
            name='is_hosteler',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
